name: "Soyjak"
source: "https://imgflip.com/memetemplate/232844223/Soyboy-Vs-Yes-Chad"
aka:
  - "Soy Boy"
  - "Soyboy Wojak"
  - "Soy Wojak"
keywords:
  - "wojak"
  - "soyjak"
  - "glasses"
  - "beard"
  - "open mouth"
  - "excited"
  - "soy"
templates:
  - "soyboy-chad"
about: "The bearded, bespectacled Wojak with a wide-open mouth, forever over-excited about something. Usually the loser of a Soyjak vs. Chad comparison."
