name: "Ah Shit, Here We Go Again"
source: "https://knowyourmeme.com/memes/ah-shit-here-we-go-again"
keywords:
  - "GTA San Andreas"
  - "CJ"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.02
    angle: 0.0
    scale_x: 1
    scale_y: 0.22
    align: center
    start: 0.0
    stop: 1.0
example:
  - "monday morning"
  - "ah shit, here we go again"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
