name: "Monkey Puppet"
source: "https://knowyourmeme.com/memes/awkward-look-monkey-puppet"
aka:
  - "Awkward Look Monkey"
  - "Pedro"
  - "Side-Eye Monkey"
keywords:
  - "monkey"
  - "puppet"
  - "awkward"
  - "side eye"
  - "nervous"
  - "looking away"
templates:
  - "monkey"
about: "Pedro the puppet from Japanese TV, giving the nervous side-eye. For every moment you would rather not be part of."
