name: "Futurama Fry"
source: "https://knowyourmeme.com/memes/futurama-fry-not-sure-if"
aka:
  - "Not Sure If"
  - "Suspicious Fry"
  - "Squinting Fry"
keywords:
  - "futurama"
  - "fry"
  - "squint"
  - "not sure if"
  - "suspicious"
  - "cartoon"
templates:
  - "fry"
about: "Philip J. Fry squinting in suspicion. Not sure if this is a meme character, or just a very good reaction image."
