name: "Mocking SpongeBob"
source: "https://knowyourmeme.com/memes/mocking-spongebob"
aka:
  - "Spongemock"
  - "Chicken SpongeBob"
  - "mOcKiNg sPoNgEbOb"
keywords:
  - "spongebob"
  - "mocking"
  - "chicken"
  - "sarcasm"
  - "alternating caps"
templates:
  - "spongebob"
about: "SpongeBob crouched like a chicken, ready to repeat whatever you said in AlTeRnAtInG cApS."
