name: "Trollface"
source: "https://imgflip.com/memetemplate/73863/Trollface"
aka:
  - "Troll Face"
  - "Coolface"
  - "Problem?"
keywords:
  - "troll"
  - "rage comic"
  - "grin"
  - "problem"
  - "mischief"
  - "black and white"
templates: []
about: "The mischievous, wide-grinning face drawn in MS Paint in 2008. The universal symbol for trolling. Problem?"
