name: "Pepe the Frog"
source: "https://imgflip.com/memetemplate/39942085/Smug-Pepe"
aka:
  - "Smug Pepe"
  - "Smug Frog"
  - "Pepe"
keywords:
  - "pepe"
  - "frog"
  - "smug"
  - "green"
  - "boy's club"
  - "hand on chin"
  - "grin"
templates: []
about: "Pepe the Frog from Matt Furie's Boy's Club, in his smug hand-on-chin pose. The internet's most versatile amphibian."
