name: "Homer's Back Fat"
source: "https://knowyourmeme.com/memes/homer-simpsons-back-fat"
keywords:
  - "Homer Simpson"
  - "back fat"
  - "sit up"
  - "Simpsons"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.5
    angle: 0.0
    scale_x: 1
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - "my legacy code"
  - "one more feature"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
