name: "Crying Cat"
source: "https://knowyourmeme.com/memes/crying-cat"
aka:
  - "Sad Cat"
  - "Schmuserkadser"
  - "Teary Cat"
keywords:
  - "cat"
  - "crying"
  - "sad"
  - "tears"
  - "thumbs up"
templates:
  - "crying-cat"
about: "A white cat with photoshopped glassy, tearful eyes. The go-to reaction for things that are sad but also kind of funny."
