name: "I'm Something of a Scientist Myself"
source: "https://knowyourmeme.com/memes/im-something-of-a-scientist-myself"
keywords:
  - "Norman Osborn"
  - "Willem Dafoe"
  - "Spider-Man"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "i copied it from stack overflow"
  - "i'm something of a scientist myself"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
