name: "SpongeBob Burning Paper"
source: "https://knowyourmeme.com/memes/spongebob-burning-paper"
keywords:
  - "SpongeBob"
  - "burning paper"
  - "fire"
  - "throw away"
  - "trash"
text:
  - style: default
    color: black
    font: thick
    anchor_x: 0.06
    anchor_y: 0.08
    angle: 0.0
    scale_x: 0.36
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
example:
  - "my sleep schedule"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
