name: "Traumatized Mr. Incredible"
source: "https://knowyourmeme.com/memes/traumatized-mr-incredible-people-who-dont-know-vs-people-who-know"
keywords:
  - "Mr. Incredible"
  - "The Incredibles"
  - "Pixar"
  - "uncanny"
  - "people who don't know"
  - "people who know"
  - "canny vs uncanny"
  - "Bob Parr"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.52
    anchor_y: 0
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "people who don't know"
  - "people who know"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
