name: "AJ Styles & Undertaker"
source: "https://knowyourmeme.com/memes/undertaker-standing-behind-aj-styles"
keywords:
  - "WWE"
  - "Undertaker"
  - "AJ Styles"
  - "looming"
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 1.0
example:
  - "me enjoying the weekend"
  - "monday"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
