name: "Dat Boi"
source: "https://imgflip.com/memetemplate/Dat-Boi"
aka:
  - "Here Come Dat Boi"
  - "O Shit Waddup"
keywords:
  - "frog"
  - "unicycle"
  - "3d"
  - "here come dat boi"
  - "waddup"
templates: []
about: "A 3D frog riding a unicycle. O shit waddup! One of 2016's most gloriously pointless memes."
