name: "Swole Doge"
source: "https://imgflip.com/memetemplate/Buff-Doge-vs-Cheems"
aka:
  - "Buff Doge"
  - "Muscular Doge"
  - "Swole Doge vs. Cheems"
keywords:
  - "doge"
  - "shiba inu"
  - "muscles"
  - "buff"
  - "strong"
  - "then vs now"
templates: []
about: "Doge with a bodybuilder's physique, flexing. The heroic then half of Swole Doge vs. Cheems."
