name: "Big Chungus"
source: "https://imgflip.com/memetemplate/163802179/Big-Chungus"
aka:
  - "Fat Bugs Bunny"
  - "Chungus"
keywords:
  - "bugs bunny"
  - "rabbit"
  - "fat"
  - "looney tunes"
  - "video game"
templates: []
about: "A rotund Bugs Bunny from a 1941 cartoon, reborn in 2018 as a fake video game cover. Absurd, round, and beloved."
