name: "Live Reaction"
source: "https://knowyourmeme.com/memes/live-tucker-reaction"
keywords:
  - "live reaction"
  - "reaction"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.6
    align: center
    start: 0.0
    stop: 1.0
example:
  - "me watching the demo break"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
