name: "Who Wants to Be a Millionaire?"
source: 
keywords:
  - "quiz"
  - "game show"
  - "four answers"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.03
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.14
    anchor_y: 0.775
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.09
    align: left
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.6
    anchor_y: 0.775
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.09
    align: left
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.14
    anchor_y: 0.885
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.09
    align: left
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.6
    anchor_y: 0.885
    angle: 0.0
    scale_x: 0.33
    scale_y: 0.09
    align: left
    start: 0.0
    stop: 1.0
example:
  - "what fixes the bug?"
  - "restart"
  - "reinstall"
  - "cry"
  - "restart again"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
