name: "Salt Bae"
source: "https://imgflip.com/memetemplate/89914538/salt-bae"
aka:
  - "Nusret Gokce"
  - "Salt Sprinkle Guy"
keywords:
  - "salt"
  - "chef"
  - "sprinkle"
  - "steak"
  - "sunglasses"
  - "flair"
templates: []
about: "Chef Nusret Gokce sprinkling salt down his forearm with maximum flair. For adding a little something extra to anything."
