name: "You Should Have Thought of That Earlier"
source: 
keywords:
  - "Tobey Maguire"
  - "Spider-Man 3"
  - "should have thought of that earlier"
  - "Eddie Brock"
  - "Peter Parker"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "but i need the weekend off"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
