name: "Dog Accepting Fate"
source: "https://knowyourmeme.com/memes/cooked-dog-dog-closing-his-eyes"
keywords:
  - "dog"
  - "acceptance"
  - "fate"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "me at the 4th meeting"
  - "of the day"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
