name: "Nyan Cat"
source: "https://imgflip.com/memetemplate/18168465/Nyan-Cat"
aka:
  - "Pop-Tart Cat"
  - "Rainbow Cat"
keywords:
  - "cat"
  - "pop tart"
  - "rainbow"
  - "pixel art"
  - "8-bit"
  - "2011"
  - "space"
templates: []
about: "A pixel cat with a Pop-Tart body flying through space on a rainbow trail. Nyan nyan nyan nyan."
