name: "Lisa Simpson's Presentation"
source: "https://knowyourmeme.com/memes/lisa-simpsons-presentation"
keywords:
  - "The Simpsons"
  - "whiteboard"
  - "PSA"
text:
  - style: default
    color: black
    font: thin
    anchor_x: 0.12
    anchor_y: 0.08
    angle: 0.0
    scale_x: 0.76
    scale_y: 0.42
    align: center
    start: 0.0
    stop: 1.0
example:
  - "memes are just modern folklore"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
