name: "I Bet He's Thinking About Other Women"
source: "https://knowyourmeme.com/memes/i-bet-hes-thinking-about-other-women"
keywords:
  - "couple in bed"
  - "thinking about"
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.3
    align: center
    start: 0.0
    stop: 1.0
example:
  - "i bet he's thinking about other women"
  - "is a hot dog a sandwich?"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
