name: "Disaster Girl"
source: "https://knowyourmeme.com/memes/disaster-girl"
aka:
  - "Zoe Roth"
  - "Girl Smiling at Fire"
  - "Evil Girl"
keywords:
  - "fire"
  - "house"
  - "smirk"
  - "girl"
  - "chaos"
  - "evil smile"
templates:
  - "disastergirl"
about: "A little girl smiles knowingly at the camera while a house burns behind her. The face of everyone who caused the problem and enjoys it."
