/**
 * Port of `app/models/template.py`. Template metadata comes from the JSON
 * manifest generated by `scripts/build-templates.ts`; images are static assets
 * (or, for custom templates, downloaded bytes).
 */
import manifest from "../generated/templates.json";
import {
  ALLOWED_EXTENSIONS,
  ANIMATED_EXTENSIONS,
  PLACEHOLDER_SUFFIX,
  type Settings,
} from "../settings";
import { sniffFormat, extensionForFormat } from "../images/format";
import { validateColor } from "../utils/colors";
import { download } from "../utils/http";
import { encode, fingerprint } from "../utils/text";
import { buildUrl, clean, isSelf, params as urlParams, schema, tryParse } from "../utils/urls";
import { Overlay, type OverlayData, type Dimensions } from "./overlay";
import { Text, type TextData } from "./text";

export interface TemplateData {
  id: string;
  name: string;
  source: string | null;
  keywords: string[];
  text: TextData[];
  example: string[];
  overlay: OverlayData[];
  files: string[];
  about?: string;
  origin?: string;
  tags?: string[];
  aka?: string[];
  descriptionSource?: string;
  /** 1-based position in the featured list, or null */
  featured?: number | null;
  /** Hidden from browsing (index, featured, related, sitemap); API and editor URL still work */
  archived?: boolean;
}

const MANIFEST = manifest as unknown as Record<string, TemplateData>;

export type ImageRef =
  | { kind: "asset"; path: string; filename: string; suffix: string }
  | { kind: "custom"; bytes: Uint8Array; filename: string; suffix: string }
  | { kind: "placeholder"; filename: string; suffix: string };

/** A downloaded overlay image, ready to be embedded when rendering. */
export interface Foreground {
  url: string;
  bytes: Uint8Array;
}

export interface CloneOptions {
  layout?: string | null;
  start?: string | null;
  stop?: string | null;
  color?: string | null;
  center?: string | null;
  scale?: string | null;
}

function stem(filename: string): string {
  const index = filename.lastIndexOf(".");
  return index <= 0 ? filename : filename.slice(0, index);
}

function suffix(filename: string): string {
  const index = filename.lastIndexOf(".");
  return index <= 0 ? "" : filename.slice(index);
}

export class Template {
  id: string;
  variant = "";
  name: string;
  source: string | null;
  keywords: string[];
  text: Text[];
  example: string[];
  overlay: Overlay[];
  files: string[];
  /** Short description of the meme (Know Your Meme excerpt or hand-written) */
  about: string;
  origin: string;
  tags: string[];
  /** Alternate names people know the meme by */
  aka: string[];
  descriptionSource: string;
  featured: number | null;
  archived: boolean;

  /** Does this template come from the manifest (vs. transient/custom)? */
  exists: boolean;
  /** Custom background bytes (downloaded), keyed by filename. */
  customImages: Map<string, Uint8Array> = new Map();
  /** Overlay images resolved by `check()`, by overlay index. */
  foregrounds: Map<number, Foreground> = new Map();
  /** Text layout: "" (default) or "top" (pads the background and moves text). */
  layout = "";

  constructor(data: Partial<TemplateData> & { id: string }, exists = false) {
    this.id = data.id;
    this.name = data.name ?? "";
    this.source = data.source ?? null;
    this.keywords = data.keywords ?? [];
    this.text = (data.text ?? [new Text().toJSON(), new Text({ anchor_x: 0.0, anchor_y: 0.8 }).toJSON()]).map(
      (t) => new Text(t),
    );
    this.example = data.example ?? ["Top Line", "Bottom Line"];
    this.overlay = (data.overlay ?? [new Overlay().toJSON()]).map((o) => new Overlay(o));
    this.files = data.files ?? [];
    this.about = data.about ?? "";
    this.origin = data.origin ?? "";
    this.tags = data.tags ?? [];
    this.aka = data.aka ?? [];
    this.descriptionSource = data.descriptionSource ?? "none";
    this.featured = data.featured ?? null;
    this.archived = data.archived ?? false;
    this.exists = exists;
  }

  toString(): string {
    return `templates/${this.id}`;
  }

  // --- registry -----------------------------------------------------------

  static get(id: string): Template {
    const template = Template.getOrNull(id);
    if (!template) throw new Error(`Unknown template: ${id}`);
    return template;
  }

  static getOrNull(id: string): Template | null {
    const data = MANIFEST[id];
    return data ? new Template(data, true) : null;
  }

  /** Like `Template.objects.get_or_create`: unknown IDs yield a transient default. */
  static getOrCreate(id: string): Template {
    return Template.getOrNull(id) ?? new Template({ id }, false);
  }

  static all(): Template[] {
    return Object.keys(MANIFEST)
      .sort()
      .map((id) => new Template(MANIFEST[id], true));
  }

  static filterValid(): Template[] {
    return Template.all().filter((t) => !t.id.startsWith("_custom") && t.valid);
  }

  /** Templates shown when browsing: valid and not archived. */
  static browsable(): Template[] {
    return Template.filterValid().filter((t) => !t.archived);
  }

  /** Curated templates from `data/featured.json`, in order. */
  static featured(): Template[] {
    return Template.browsable()
      .filter((t) => t.featured !== null)
      .sort((a, b) => (a.featured ?? 0) - (b.featured ?? 0));
  }

  // --- properties ---------------------------------------------------------

  get valid(): boolean {
    return !this.id.startsWith("_") && !this.name.includes("/") && this.image.suffix !== PLACEHOLDER_SUFFIX;
  }

  private stylesCache: string[] | null = null;

  get styles(): string[] {
    if (this.stylesCache) return this.stylesCache;
    const styles: string[] = [];
    for (const file of this.files) {
      const s = stem(file);
      if (!s || s[0] === "." || s[0] === "_") continue;
      if (s !== "config" && s !== "default") {
        styles.push(s);
      } else if (file === "default.gif") {
        styles.push("animated");
      }
    }
    if (styles.length || !this.overlayIsDefault()) styles.push("default");
    styles.sort();
    this.stylesCache = styles;
    return styles;
  }

  overlayIsDefault(): boolean {
    return this.overlay.length === 1 && this.overlay[0].isDefault();
  }

  get animatedImage(): boolean {
    return this.styles.includes("animated");
  }

  get animatedText(): boolean {
    return this.text.some((text) => text.animated);
  }

  get image(): ImageRef {
    return this.getImage();
  }

  private makeRef(filename: string): ImageRef {
    const custom = this.customImages.get(filename);
    if (custom) return { kind: "custom", bytes: custom, filename, suffix: suffix(filename) };
    return {
      kind: "asset",
      path: `/templates/${encodeURIComponent(this.id)}/${encodeURIComponent(filename)}`,
      filename,
      suffix: suffix(filename),
    };
  }

  getImage(style = "default", animated = false): ImageRef {
    if (style === "animated") {
      style = "default";
      animated = true;
    }
    style = style || "default";

    if (schema(style)) {
      // Overlay URLs are composited at render time; the background stays default.
      style = fingerprint(`${style}${this.overlay.map(String).join(", ")}`);
    }

    const paths = this.files.filter((file) => stem(file) === style && suffix(file) !== PLACEHOLDER_SUFFIX);

    if (animated) {
      const gif = paths.find((file) => suffix(file) === ".gif");
      if (gif) return this.makeRef(gif);
      if (paths.length) return this.makeRef(paths[0]);
    } else {
      const still = paths.find((file) => suffix(file) !== ".gif");
      if (still) return this.makeRef(still);
      if (paths.length) return this.makeRef(paths[0]);
    }

    if (this.files.includes("default.gif")) {
      return this.makeRef("default.gif");
    }

    if (style === "default" && !animated) {
      console.info(`No default background image for template: ${this.id}`);
      return { kind: "placeholder", filename: "default" + PLACEHOLDER_SUFFIX, suffix: PLACEHOLDER_SUFFIX };
    }

    if (animated) {
      console.info(`Using static image to animate template: ${this.id}`);
    } else {
      console.warn(`Style ${JSON.stringify(style)} not available for template: ${this.id}`);
    }
    return this.getImage();
  }

  // --- JSON / URLs --------------------------------------------------------

  toJSON(settings: Settings) {
    const base = settings.BASE_URL;
    return {
      id: this.id,
      name: this.name,
      lines: this.text.length,
      overlays: this.styles.length ? this.overlay.length : 0,
      styles: this.styles,
      blank: `${base}/images/${this.id}${settings.DEFAULT_SUFFIX}`,
      example: {
        text: this.example.some(Boolean) ? this.example : [],
        url: this.buildExampleUrl(settings),
      },
      source: this.source,
      keywords: this.keywords,
      _self: this.buildSelfUrl(settings),
    };
  }

  buildSelfUrl(settings: Settings): string {
    return `${settings.BASE_URL}/templates/${this.id}`;
  }

  buildExampleUrl(settings: Settings, { extension = "", external = true } = {}): string {
    extension = extension || this.defaultExtension(settings);
    const base = external ? settings.BASE_URL : "";
    const url = buildUrl(base, `/images/${this.id}/${encode(this.example)}.${extension}`);
    return clean(url);
  }

  buildCustomUrl(
    settings: Settings,
    textLines: string[],
    {
      normalize = true,
      extension = "",
      background = "",
      style = "",
      layout = "",
      font = "",
    }: {
      normalize?: boolean;
      extension?: string;
      background?: string;
      style?: string;
      layout?: string;
      font?: string;
    } = {},
  ): string {
    textLines = [...textLines];
    if (normalize) {
      for (let index = 0; index < this.text.length && index < textLines.length; index++) {
        textLines[index] = this.text[index].normalize(textLines[index]);
      }
    }
    if (!extension && background) {
      const parsed = tryParse(background);
      const segments = (parsed ? parsed.pathname : background).split("/").filter(Boolean);
      if (segments.length) {
        const last = segments[segments.length - 1];
        extension = last.split(".").pop() ?? "";
      }
    }
    if (!ALLOWED_EXTENSIONS.has(extension)) {
      extension = this.defaultExtension(settings);
    }
    if (style === "default") {
      style = "";
    } else if (style === "animated") {
      style = "";
      if (!ANIMATED_EXTENSIONS.has(extension)) {
        extension = settings.DEFAULT_ANIMATED_EXTENSION;
      }
    }
    if (layout === "default") layout = "";

    const templateId = this.id === "_custom" ? "custom" : this.id;
    const url = buildUrl(
      settings.BASE_URL,
      `/images/${templateId}/${encode(textLines)}.${extension}`,
      urlParams({ background, style, layout, font }),
    );
    return clean(url);
  }

  defaultExtension(settings: Settings): string {
    return this.animatedImage ? settings.DEFAULT_ANIMATED_EXTENSION : settings.DEFAULT_STATIC_EXTENSION;
  }

  /** Cache key equivalent of `build_path` (the on-disk filename in Python). */
  buildPath(
    textLines: string[],
    fontName: string,
    style: string,
    size: Dimensions,
    watermark: string,
    extension: string,
    frames = 0,
  ): string {
    const slug = encode(textLines);
    let identifier = `[${this.text.map(String).join(", ")}]` + fontName + style + `(${size[0]}, ${size[1]})` + watermark;
    if (!this.overlayIsDefault()) identifier += `[${this.overlay.map(String).join(", ")}]`;
    if (frames) identifier += String(frames);
    identifier += this.layout + [...this.foregrounds.values()].map((f) => f.url).join(",");
    const fp = fingerprint(identifier, { prefix: "" });
    return `${this.id}${this.variant}/${slug}.${fp}.${extension}`;
  }

  // --- custom backgrounds -------------------------------------------------

  /**
   * Resolve a URL into a template: URLs pointing at this service map back to
   * their template; any other URL becomes a `_custom-<sha1>` template with the
   * downloaded image as its background.
   */
  static async create(url: string, { host = "", cacheTtl = 86400 } = {}): Promise<Template> {
    let parsed = tryParse(url);
    if (!parsed) {
      // Not a URL at all: an image-less custom template, so callers report 415
      console.error(`Invalid URL: ${url}`);
      return new Template({ id: fingerprint(url) || "_custom", name: url }, false);
    }

    if (isSelf(parsed, host)) {
      console.info(`Handling template URL: ${url}`);
      const segments = parsed.pathname.split("/").filter(Boolean);
      if (segments.length > 1) {
        const id = stem(segments[1]);
        if (id !== "custom") {
          return Template.getOrNull(id) ?? Template.get("_error");
        }
        const background = parsed.searchParams.get("background");
        if (!background) return Template.get("_error");
        url = background;
        parsed = tryParse(url);
        if (!parsed) {
          console.error(`Invalid URL: ${url}`);
          return new Template({ id: fingerprint(url) || "_custom", name: url }, false);
        }
      }
    }

    const id = fingerprint(url);
    const template = new Template({ id, name: url }, false);

    let ext = suffix(parsed.pathname);
    if (!ext || ext.length > 10) {
      console.warn(`Unable to determine image extension: ${url}`);
      ext = PLACEHOLDER_SUFFIX;
    }

    console.info(`Fetching background ${url}`);
    const result = await download(url, cacheTtl);
    if (!result) return template;

    const format = sniffFormat(result.bytes);
    if (!format) {
      console.error(`Not an image: ${url}`);
      return template;
    }
    if (ext === PLACEHOLDER_SUFFIX) ext = extensionForFormat(format);

    const filename = "default" + ext;
    template.files = [filename];
    template.customImages.set(filename, result.bytes);
    if (format === "gif") template.stylesCache = null;
    return template;
  }

  /** Does the template have a background image to render? */
  get hasImage(): boolean {
    return this.image.kind !== "placeholder";
  }

  /**
   * Validate a `style` value: a known style name, or one or more overlay image
   * URLs (comma-separated) which are downloaded and attached as foregrounds.
   */
  async check(style: string, { cacheTtl = 86400 } = {}): Promise<boolean> {
    if (style === null || style === undefined || style === "" || style === "default") return true;
    if (this.styles.includes(style)) return true;

    if (!schema(style)) {
      console.error(`Invalid style for ${this.id} template: ${style}`);
      return false;
    }

    const urls = style
      .split(",")
      .map((u) => u.trim())
      .filter(Boolean);
    console.info(`Embedding ${urls.length} overlay image(s)`);

    let embedded = 0;
    for (const [index, url] of urls.entries()) {
      if (await this.embed(index, url, cacheTtl)) embedded += 1;
    }
    return embedded === urls.length;
  }

  private async embed(index: number, url: string, cacheTtl: number): Promise<boolean> {
    url = url.trim();
    if (url === "" || url === "default") return true;

    if (index >= this.overlay.length) {
      console.error(`Template ${JSON.stringify(this.id)} only supports ${this.overlay.length} overlay(s)`);
    }

    const result = await download(url, cacheTtl);
    if (!result) return false;
    if (!sniffFormat(result.bytes)) {
      console.error(`Overlay is not an image: ${url}`);
      return false;
    }
    this.foregrounds.set(index, { url, bytes: result.bytes });
    return true;
  }

  // --- per-request customization ------------------------------------------

  clone(options: URLSearchParams, lines = 1, style = "default", { animated = false } = {}): Template {
    const layout = options.get("layout") ?? "default";
    const start = options.get("start") ?? "";
    const stop = options.get("stop") ?? "";
    const color = options.get("color");
    const center = options.get("center");
    const scale = options.get("scale");

    const identifiers = [start, stop, color, center, scale].filter((v) => v).map(String);
    if (layout === "top") identifiers.push(layout, String(lines));
    const variant = fingerprint(identifiers.join("|"), { prefix: "." });

    const template = new Template(
      {
        id: this.id,
        name: this.name,
        source: this.source,
        keywords: this.keywords,
        text: this.text.map((t) => t.toJSON()),
        example: this.example,
        overlay: this.overlay.map((o) => o.toJSON()),
        files: this.files,
        about: this.about,
        origin: this.origin,
        tags: this.tags,
        aka: this.aka,
        descriptionSource: this.descriptionSource,
        featured: this.featured,
        archived: this.archived,
      },
      this.exists,
    );
    template.variant = variant;
    template.customImages = this.customImages;
    template.foregrounds = new Map(this.foregrounds);

    template.animate(start, stop);
    template.customize(color, center, scale);
    template.position(layout, lines, style, animated);
    return template;
  }

  animate(start = "0.2,0.6", stop = "1.0,1.0"): void {
    const parse = (value: string) => value.split(",").filter(Boolean).map(Number);
    const starts = parse(start);
    const stops = parse(stop);
    if ([...starts, ...stops].some((n) => Number.isNaN(n))) {
      console.error(`Invalid text animation: start=${JSON.stringify(start)} stop=${JSON.stringify(stop)}`);
      return;
    }
    starts.forEach((value, index) => {
      if (index < this.text.length) this.text[index].start = value;
    });
    stops.forEach((value, index) => {
      if (index < this.text.length) this.text[index].stop = value;
    });
    if (starts.length || stops.length) {
      console.info(`Updated ${this} with: starts=[${starts}] stops=[${stops}]`);
    }
  }

  customize(color: string | null, center: string | null, scale: string | number | null): void {
    if (color) {
      const values = color.split(",").filter(Boolean);
      values.forEach((value, index) => {
        if (index >= this.text.length) return;
        const [normalized, valid] = validateColor(value);
        this.text[index].color = valid && normalized ? normalized : new Text().color;
      });
    }
    if (center) {
      const xy = center.split(",").map(Number);
      if (xy.length === 2 && xy.every((n) => !Number.isNaN(n))) {
        this.overlay[0].center_x = xy[0];
        this.overlay[0].center_y = xy[1];
      } else {
        console.error(`Invalid overlay: center=${JSON.stringify(center)}`);
      }
    }
    if (scale) {
      const value = Number(scale);
      if (Number.isNaN(value)) {
        console.error(`Invalid overlay: scale=${JSON.stringify(scale)}`);
      } else {
        this.overlay[0].scale = value;
      }
    }
  }

  position(layout: string, lines: number, _style: string, _animated: boolean): void {
    if (layout === "top") {
      this.text = [];
      for (let index = 0; index < lines; index++) {
        this.text.push(
          new Text({
            style: "none",
            color: "black",
            font: "thin",
            anchor_x: 0.01,
            anchor_y: index * 0.1,
            scale_x: 0.99,
            scale_y: 0.2 / lines,
            align: "left",
          }),
        );
      }
      this.layout = "top";
    }
  }

  /** Everything a person might search by: name, aliases, keywords, tags, example text, description. */
  get searchText(): string {
    return [this.id, this.name, ...this.aka, ...this.keywords, ...this.tags, ...this.example, this.about, this.origin]
      .join(" ")
      .toLowerCase();
  }

  /** The API's `filter` semantics (same as the Python service): name, keywords, example. */
  matches(query: string): boolean {
    const keywords = this.keywords.map((k) => k.toLowerCase()).join(" ");
    const example = this.example.map((e) => e.toLowerCase()).join(" ");
    return (
      this.id.includes(query) ||
      this.name.toLowerCase().includes(query) ||
      keywords.includes(query) ||
      example.includes(query)
    );
  }

  /** Full-text search for the web pages: every word must appear in `searchText`. */
  matchesText(query: string): boolean {
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) return true;
    const haystack = this.searchText;
    return terms.every((term) => haystack.includes(term));
  }
}
