name: "Feels Bad Man"
source: "https://knowyourmeme.com/memes/feels-bad-man-sad-frog"
aka:
  - "Sad Frog"
  - "Sad Pepe"
  - "Feels Bad"
keywords:
  - "pepe"
  - "frog"
  - "sad"
  - "feels bad man"
  - "crying"
  - "green"
templates:
  - "sadfrog"
about: "The sad, droopy-eyed Pepe from Boy's Club. Feels bad, man. The original melancholy frog."
