name: "Train Hitting a School Bus"
source: "https://knowyourmeme.com/memes/train-hitting-school-bus"
keywords:
  - "train"
  - "school bus"
  - "crash"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.02
    angle: 0.0
    scale_x: 1
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.52
    angle: 0.0
    scale_x: 1
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - "my plans"
  - "monday"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
