name: "Are They in the Room With Us Right Now?"
source: 
keywords:
  - "in the room with us"
  - "therapist"
  - "paranoid"
  - "right now"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "the users who need this feature"
  - "are they in the room with us right now?"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
