name: "Why Can't You Just Be Normal"
source: "https://knowyourmeme.com/memes/why-cant-you-just-be-normal"
keywords:
  - "The Babadook"
  - "just be normal"
  - "screaming"
  - "mother"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0.0
    scale_x: 1
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.35
    anchor_y: 0.6
    angle: 0.0
    scale_x: 0.65
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "why can't you just be normal?"
  - "*screams in javascript*"
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
